// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAGofp7OLyfiG6YwymeUgNCVO_VVUhHpk',
    appId: '1:696682697975:web:5d2b9dd02af90f9c7f6ff2',
    messagingSenderId: '696682697975',
    projectId: 'taskapp-b7a8f',
    authDomain: 'taskapp-b7a8f.firebaseapp.com',
    storageBucket: 'taskapp-b7a8f.appspot.com',
    measurementId: 'G-CL6T8WP53Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD87Ve4OVkJqmHqsB9kb3fbl3ViHU8JUDQ',
    appId: '1:696682697975:android:1741524f169ad6a47f6ff2',
    messagingSenderId: '696682697975',
    projectId: 'taskapp-b7a8f',
    storageBucket: 'taskapp-b7a8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCevNafe5T2Possnytjtqblr5vX4wCzBIM',
    appId: '1:696682697975:ios:fd20cbc33614cf627f6ff2',
    messagingSenderId: '696682697975',
    projectId: 'taskapp-b7a8f',
    storageBucket: 'taskapp-b7a8f.appspot.com',
    androidClientId: '696682697975-b27t6gp1svn2eio4jv6c7e1udelenlp0.apps.googleusercontent.com',
    iosClientId: '696682697975-spa8cnd97c3l0sq842s58oeag9pf9mji.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskApp',
  );
}
